### ISSUE TITLE
Integrate Travis CI with Gitter

### ISSUE THREAD

**Issue by desyncr** [zsh-users/antigen#472]
See https://docs.travis-ci.com/user/notifications.

```
Instructions
You need to configure your Travis job to send Webhook notifications.

Add the following to your .travis.yml configuration:

notifications:
  webhooks:
    urls:
      - YOUR_WEBHOOK_URL
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

```

Should go to `antigen-zsh/builds` channel.
